# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/ayham-mamoun/Desktop/git repos/T.T.B.G"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/ayham-mamoun/Desktop/git repos/T.T.B.G"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ayham-mamoun/Desktop/git repos/T.T.B.G/CMakeFiles" "/home/ayham-mamoun/Desktop/git repos/T.T.B.G/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ayham-mamoun/Desktop/git repos/T.T.B.G/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TTBG-API

# Build rule for target.
TTBG-API: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TTBG-API
.PHONY : TTBG-API

# fast build rule for target.
TTBG-API/fast:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/build
.PHONY : TTBG-API/fast

#=============================================================================
# Target rules for targets named TTBG

# Build rule for target.
TTBG: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TTBG
.PHONY : TTBG

# fast build rule for target.
TTBG/fast:
	$(MAKE) -f CMakeFiles/TTBG.dir/build.make CMakeFiles/TTBG.dir/build
.PHONY : TTBG/fast

T.T.B.G-API/core/GA/Individual.o: T.T.B.G-API/core/GA/Individual.cpp.o

.PHONY : T.T.B.G-API/core/GA/Individual.o

# target to build an object file
T.T.B.G-API/core/GA/Individual.cpp.o:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/GA/Individual.cpp.o
.PHONY : T.T.B.G-API/core/GA/Individual.cpp.o

T.T.B.G-API/core/GA/Individual.i: T.T.B.G-API/core/GA/Individual.cpp.i

.PHONY : T.T.B.G-API/core/GA/Individual.i

# target to preprocess a source file
T.T.B.G-API/core/GA/Individual.cpp.i:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/GA/Individual.cpp.i
.PHONY : T.T.B.G-API/core/GA/Individual.cpp.i

T.T.B.G-API/core/GA/Individual.s: T.T.B.G-API/core/GA/Individual.cpp.s

.PHONY : T.T.B.G-API/core/GA/Individual.s

# target to generate assembly for a file
T.T.B.G-API/core/GA/Individual.cpp.s:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/GA/Individual.cpp.s
.PHONY : T.T.B.G-API/core/GA/Individual.cpp.s

T.T.B.G-API/core/GA/Population.o: T.T.B.G-API/core/GA/Population.cpp.o

.PHONY : T.T.B.G-API/core/GA/Population.o

# target to build an object file
T.T.B.G-API/core/GA/Population.cpp.o:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/GA/Population.cpp.o
.PHONY : T.T.B.G-API/core/GA/Population.cpp.o

T.T.B.G-API/core/GA/Population.i: T.T.B.G-API/core/GA/Population.cpp.i

.PHONY : T.T.B.G-API/core/GA/Population.i

# target to preprocess a source file
T.T.B.G-API/core/GA/Population.cpp.i:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/GA/Population.cpp.i
.PHONY : T.T.B.G-API/core/GA/Population.cpp.i

T.T.B.G-API/core/GA/Population.s: T.T.B.G-API/core/GA/Population.cpp.s

.PHONY : T.T.B.G-API/core/GA/Population.s

# target to generate assembly for a file
T.T.B.G-API/core/GA/Population.cpp.s:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/GA/Population.cpp.s
.PHONY : T.T.B.G-API/core/GA/Population.cpp.s

T.T.B.G-API/core/GA/_GA.o: T.T.B.G-API/core/GA/_GA.cpp.o

.PHONY : T.T.B.G-API/core/GA/_GA.o

# target to build an object file
T.T.B.G-API/core/GA/_GA.cpp.o:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/GA/_GA.cpp.o
.PHONY : T.T.B.G-API/core/GA/_GA.cpp.o

T.T.B.G-API/core/GA/_GA.i: T.T.B.G-API/core/GA/_GA.cpp.i

.PHONY : T.T.B.G-API/core/GA/_GA.i

# target to preprocess a source file
T.T.B.G-API/core/GA/_GA.cpp.i:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/GA/_GA.cpp.i
.PHONY : T.T.B.G-API/core/GA/_GA.cpp.i

T.T.B.G-API/core/GA/_GA.s: T.T.B.G-API/core/GA/_GA.cpp.s

.PHONY : T.T.B.G-API/core/GA/_GA.s

# target to generate assembly for a file
T.T.B.G-API/core/GA/_GA.cpp.s:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/GA/_GA.cpp.s
.PHONY : T.T.B.G-API/core/GA/_GA.cpp.s

T.T.B.G-API/core/utils/files/File_Manager.o: T.T.B.G-API/core/utils/files/File_Manager.cpp.o

.PHONY : T.T.B.G-API/core/utils/files/File_Manager.o

# target to build an object file
T.T.B.G-API/core/utils/files/File_Manager.cpp.o:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/utils/files/File_Manager.cpp.o
.PHONY : T.T.B.G-API/core/utils/files/File_Manager.cpp.o

T.T.B.G-API/core/utils/files/File_Manager.i: T.T.B.G-API/core/utils/files/File_Manager.cpp.i

.PHONY : T.T.B.G-API/core/utils/files/File_Manager.i

# target to preprocess a source file
T.T.B.G-API/core/utils/files/File_Manager.cpp.i:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/utils/files/File_Manager.cpp.i
.PHONY : T.T.B.G-API/core/utils/files/File_Manager.cpp.i

T.T.B.G-API/core/utils/files/File_Manager.s: T.T.B.G-API/core/utils/files/File_Manager.cpp.s

.PHONY : T.T.B.G-API/core/utils/files/File_Manager.s

# target to generate assembly for a file
T.T.B.G-API/core/utils/files/File_Manager.cpp.s:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/utils/files/File_Manager.cpp.s
.PHONY : T.T.B.G-API/core/utils/files/File_Manager.cpp.s

T.T.B.G-API/core/utils/files/csv/csv_loader.o: T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.o

.PHONY : T.T.B.G-API/core/utils/files/csv/csv_loader.o

# target to build an object file
T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.o:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.o
.PHONY : T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.o

T.T.B.G-API/core/utils/files/csv/csv_loader.i: T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.i

.PHONY : T.T.B.G-API/core/utils/files/csv/csv_loader.i

# target to preprocess a source file
T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.i:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.i
.PHONY : T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.i

T.T.B.G-API/core/utils/files/csv/csv_loader.s: T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.s

.PHONY : T.T.B.G-API/core/utils/files/csv/csv_loader.s

# target to generate assembly for a file
T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.s:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.s
.PHONY : T.T.B.G-API/core/utils/files/csv/csv_loader.cpp.s

T.T.B.G-API/core/utils/files/csv/csv_saver.o: T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.o

.PHONY : T.T.B.G-API/core/utils/files/csv/csv_saver.o

# target to build an object file
T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.o:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.o
.PHONY : T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.o

T.T.B.G-API/core/utils/files/csv/csv_saver.i: T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.i

.PHONY : T.T.B.G-API/core/utils/files/csv/csv_saver.i

# target to preprocess a source file
T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.i:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.i
.PHONY : T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.i

T.T.B.G-API/core/utils/files/csv/csv_saver.s: T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.s

.PHONY : T.T.B.G-API/core/utils/files/csv/csv_saver.s

# target to generate assembly for a file
T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.s:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.s
.PHONY : T.T.B.G-API/core/utils/files/csv/csv_saver.cpp.s

T.T.B.G-API/driver/API_driver.o: T.T.B.G-API/driver/API_driver.cpp.o

.PHONY : T.T.B.G-API/driver/API_driver.o

# target to build an object file
T.T.B.G-API/driver/API_driver.cpp.o:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/driver/API_driver.cpp.o
.PHONY : T.T.B.G-API/driver/API_driver.cpp.o

T.T.B.G-API/driver/API_driver.i: T.T.B.G-API/driver/API_driver.cpp.i

.PHONY : T.T.B.G-API/driver/API_driver.i

# target to preprocess a source file
T.T.B.G-API/driver/API_driver.cpp.i:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/driver/API_driver.cpp.i
.PHONY : T.T.B.G-API/driver/API_driver.cpp.i

T.T.B.G-API/driver/API_driver.s: T.T.B.G-API/driver/API_driver.cpp.s

.PHONY : T.T.B.G-API/driver/API_driver.s

# target to generate assembly for a file
T.T.B.G-API/driver/API_driver.cpp.s:
	$(MAKE) -f CMakeFiles/TTBG-API.dir/build.make CMakeFiles/TTBG-API.dir/T.T.B.G-API/driver/API_driver.cpp.s
.PHONY : T.T.B.G-API/driver/API_driver.cpp.s

T.T.B.G/app_entry.o: T.T.B.G/app_entry.cpp.o

.PHONY : T.T.B.G/app_entry.o

# target to build an object file
T.T.B.G/app_entry.cpp.o:
	$(MAKE) -f CMakeFiles/TTBG.dir/build.make CMakeFiles/TTBG.dir/T.T.B.G/app_entry.cpp.o
.PHONY : T.T.B.G/app_entry.cpp.o

T.T.B.G/app_entry.i: T.T.B.G/app_entry.cpp.i

.PHONY : T.T.B.G/app_entry.i

# target to preprocess a source file
T.T.B.G/app_entry.cpp.i:
	$(MAKE) -f CMakeFiles/TTBG.dir/build.make CMakeFiles/TTBG.dir/T.T.B.G/app_entry.cpp.i
.PHONY : T.T.B.G/app_entry.cpp.i

T.T.B.G/app_entry.s: T.T.B.G/app_entry.cpp.s

.PHONY : T.T.B.G/app_entry.s

# target to generate assembly for a file
T.T.B.G/app_entry.cpp.s:
	$(MAKE) -f CMakeFiles/TTBG.dir/build.make CMakeFiles/TTBG.dir/T.T.B.G/app_entry.cpp.s
.PHONY : T.T.B.G/app_entry.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TTBG-API"
	@echo "... TTBG"
	@echo "... T.T.B.G-API/core/GA/Individual.o"
	@echo "... T.T.B.G-API/core/GA/Individual.i"
	@echo "... T.T.B.G-API/core/GA/Individual.s"
	@echo "... T.T.B.G-API/core/GA/Population.o"
	@echo "... T.T.B.G-API/core/GA/Population.i"
	@echo "... T.T.B.G-API/core/GA/Population.s"
	@echo "... T.T.B.G-API/core/GA/_GA.o"
	@echo "... T.T.B.G-API/core/GA/_GA.i"
	@echo "... T.T.B.G-API/core/GA/_GA.s"
	@echo "... T.T.B.G-API/core/utils/files/File_Manager.o"
	@echo "... T.T.B.G-API/core/utils/files/File_Manager.i"
	@echo "... T.T.B.G-API/core/utils/files/File_Manager.s"
	@echo "... T.T.B.G-API/core/utils/files/csv/csv_loader.o"
	@echo "... T.T.B.G-API/core/utils/files/csv/csv_loader.i"
	@echo "... T.T.B.G-API/core/utils/files/csv/csv_loader.s"
	@echo "... T.T.B.G-API/core/utils/files/csv/csv_saver.o"
	@echo "... T.T.B.G-API/core/utils/files/csv/csv_saver.i"
	@echo "... T.T.B.G-API/core/utils/files/csv/csv_saver.s"
	@echo "... T.T.B.G-API/driver/API_driver.o"
	@echo "... T.T.B.G-API/driver/API_driver.i"
	@echo "... T.T.B.G-API/driver/API_driver.s"
	@echo "... T.T.B.G/app_entry.o"
	@echo "... T.T.B.G/app_entry.i"
	@echo "... T.T.B.G/app_entry.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

